### ISSUE TITLE
Set-up layout manager

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#29]
* Integrate Flex Layout from geppetto-ui 
* Reuse canvas performance prototype

**Comment by afonsobspinto** [comment]
![image](https://user-images.githubusercontent.com/19196034/125495664-0b8184ef-bcfc-4d9c-8d67-9477ad23f0fe.png)

**Comment by afonsobspinto** [comment]
Some notes:
- Added some dummy buttons to prototype/test the functionality.
- Still to solve some CSS issues with the Canvas size.

- Had to fix the threejs version #120 
  - This changed the yarn.lock, some other packages like material UI also updated so I had to do some small compatibility changes (CreateMUITheme -> CreateTheme)
- Update craco webpack to use url-loader for obj files  

I don't think I should create a PR for this one because after speaking with @filippomc I understood that the widget config should be used to send **static** data that allows reusing components, which is not what I'm doing.

So as part of #22 we should integrate some of this poc and add/follow the strategy:
1 -  Make the canvas data (and any other props) part of the redux state.
2 -  Create a canvas container to connect redux state to canvas props
3 - Profit from reusable components
