### ISSUE TITLE
Customise canvas controls as per mockups

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#31]
Controls:
- reset camera
- zoom in
- zoom out
- expand / full screen - this will have to be binded to the flexlayout action to expand the tab full screen.

Place holders for the other components (we do not implement each component in this card but just put place holder for the controls):
- icon for play/pause animation
- icon for synchronization
- icon for recording 
- icon for download objs/img
- icon for for layers (Strata objs)
- icon for dev stage slider
- icon for colorpicker
- icon for switching background from dark to light.

it would be ideal to make possible to disable a control so that the button for that control is not displayed when the prop for that is set to false, this will give us flexibility since few of the controls above are still under discussion (recording, synchronization).

**Comment by ddelpiano** [comment]
We can save a bit of time here using the same controls we have in VFB

**Comment by lrebscher** [comment]
[CameraControls](https://github.com/MetaCell/geppetto-meta/blob/development/geppetto.js/geppetto-ui/src/camera-controls/CameraControls.js) is the default set of icons for the Canvas.

Any React component that matches the props of this Component can be added to the Canvas by specifying it in the camera configuration, see [this example](https://github.com/MetaCell/geppetto-meta/blob/990f6f4b7094466862dcf58a2122976ccddd1ad0/examples/redux-react-app/src/components/CanvasExample.js#L25).

Since we add new buttons we should implement a new Controls component specific to YALE reusing some of the code of CameraControls.js (e.g. available camera actions).

Not every button will trigger an action passed to the `cameraControlsHandler`. E.g. icon for dev stage slider is independent of the Canvas scene and will open a popup. In that case we don't need to call the `cameraControlsHandler`.
