### ISSUE TITLE
Strapi plugin implementation

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#77]

**Comment by lrebscher** [comment]
**Description**

The plugin should provide a simple UI view allowing a user to upload a CSV file and import the content into Strapi CMS

During the preprocessing we generate a set of CSV files that describe instances of a collection (e.g. Neurons collection). We want to populate the database by importing the CSV files with the custom Strapi plugin.

**Tasks**

* Implement minimal UI upload form (based on Strapi's tutorial, but we don't need the history page). User can upload a single CSV and click on an "Import" button
* Parse the uploaded CSV & create instances that match the respective collection format  
* Add these instances to Strapi by using the endpoints of the respective collection

Most entities contain file paths that point to objs or other media files. Since we are waiting for information about the storage of these files, we should focus solely on the logic of executing a [file upload with Strapi](https://strapi.io/documentation/developer-docs/latest/development/plugins/upload.html#upload-files) that links file and instance. File retrieval and resolution of the file paths will be part of a connector in a separate issue.

**Comment by afonsobspinto** [comment]
Some dude created [this](https://github.com/afonsobspinto/strapi-plugin-import-csv). Seems to do what we wanted

**Comment by ddelpiano** [comment]
moving this to icebox waiting for open questions about the data to be answered.

**Comment by afonsobspinto** [comment]
I created a [new branch](https://github.com/afonsobspinto/strapi-plugin-import-csv/tree/feature/77) that automatically fills the columns based on the conditions:
- The csv headers match with model attributes 
- The match on and related column are the 'uid' attribute

Both conditions are met in NeuroScan.

Some time measurements for  the biggest csv file [synapses_300 ](https://docs.google.com/spreadsheets/d/11aNEORjHAcZHfLYYM3DVLtmDuIY3ZY5ENSm-eSgvZ6U/edit?usp=sharing) (10688 rows):
Analyzing the file: ~15 minutes 
Importing the content: ~15 minutes
Importing relations: ~30 minutes

**Comment by afonsobspinto** [comment]
Imo can be closed and now tracked on #142. cc @ddelpiano
