### ISSUE TITLE
Create data model with its entities and relations

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#80]

**Comment by afonsobspinto** [comment]
Some notes/questions on the data model:

Common problems:
- Metadata missing
- How to model stages/timepoints?


(data related issues are coming from the google drive data and not the one in dropbox. Dropbox data might have solved some of the issues.)

Contacts:
1. If it's true that we can have multiple Pre->Post contacts we need a new unique identifier for contacts. 
2. Contacts missing weight attribute on the model

data related:
a) There are contacts without weight information (do not appear in the csv)
b) There are contacts without obj files (only appear in the csv)

Synapses:

3. Because we can have multiple synapses with the same pre/post/type we need a new unique identifier for synapses. Section + Zx looks like a good candidate but see d)

4. If there's any value in knowing if the synapse is pre or post we may want to add a new Enumeration attribute.

data related:
c) If pre and post-synapses are independent, are Synapses/ADAL_PreSyn/Adal->AIBR and Syanpses/AIBR_PostSyn/Adal->AIBR different entites?
d) What's the difference between the following files: 
- SketchVolumeViewer_AIBRchemicalDVC_RIBL_AVDR_certainJSHJSH060_zs1_AIBRchemicalDVC_RIBL_AVDR_certainJSHJSH060_zs1_1_1_0000preSyn_**yellow-1**.obj

- SketchVolumeViewer_AIBRchemicalDVC_RIBL_AVDR_certainJSHJSH060_zs1_AIBRchemicalDVC_RIBL_AVDR_certainJSHJSH060_zs1_1_1_0000preSyn_**plum-0**.obj

e) already an open question but, Are these objs describing independent synapses?
- AIAR -> [AIBR,  AWCR] (SketchVolumeViewer_AIARchemicalAIBR_AWCR_certainJSHJSH105_zs2_AIARchemicalAIBR_AWCR_certainJSHJSH105_zs2_1_1_0000postSyn_green-0.obj)
- AIAR -> [AIBR, AWCR] (SketchVolumeViewer_AIARchemicalAIBR_AWCR_certainJSHJSH157_zs3_AIARchemicalAIBR_AWCR_certainJSHJSH157_zs3_1_1_0000postSyn_green-0.obj)
  
Neurons:
5. Missing lineage attribute
6. Missing location attribute

data related:
f) Some neurons are referenced but we don't have the obj (yet).

**Comment by lrebscher** [comment]
> Neurons f) Some neurons are referenced but we don't have the obj (yet).

seems to be fixed in the Dropbox neuron folder

**Comment by afonsobspinto** [comment]
Strapi Changelog:

Contacts:
- name -> uid
- files -> file (assuming 1 file per contact)
- +weight
- +timepoints (as json - to allow arrays)

DevelopmentStages:
- name -> uid
- +name
- +begin
- +end
- +order
- +timepoints
- +promoterDB (promoterDB and NeuroScan can't share the same development stage with this boolean -> change to enumeration?)

Neuron:
- name -> uid
- files -> file (assuming 1 file per neuron)
- -developmental_stages
- +timepoints
- +embryonic
- +lineage
- +location

Synapses:
- name -> uid
- neuronPost -> neuronsPost (changed relationship from one-to-one to one-to-many)
- files -> file (assuming 1 file per synapse)
- +timepoints
- +metadata
- +section
- +zs
- +position (enumeration pre|post)

+Promoter:
- +uid
- +files
- +cellsByLineaging
- +metadata
- +timepoints

**Comment by lrebscher** [comment]
@afonsobspinto  for DevelopmentalStage the `name` won't be unique, since we can have two stages with the same name "Hatching" but with different time units. 

So as uid we can do sth like "promoterdb-hatching" and "neuroscan-hatching", that will be set manually in the CSV.

We have will have no overlap between PromoterDb and NeuroSCAN, that's why I chose the boolean flag

**Comment by lrebscher** [comment]
I would keep `file` as `files` even if Contact or Synapse currently has only one file. 

Out of two reasons:
* it's likely that the requirements changes here again
* we simplify the logic in the frontend because we it's always `instance.files` and we use the same logic to get file for specified dev stage

**Comment by afonsobspinto** [comment]
Changes applied
